### ISSUE TITLE
Unknown encoder 'h264'

### ISSUE THREAD

**Issue by 3c** [Kernald/ffmpeg-android#3]
commid is 

```
-y -i /sdcard/test.mp4 -vf crop=480:480:0:0 -acodec aac -b:a 44000 -vcodec h264 -b:v 960000 -strict -2 /sdcard/test1.mp4
```

report  Unknown encoder 'h264' .

**Comment by Kernald** [comment]
This build of ffmpeg doesn't include any h264 encoder. You'll have to build it with it enabled (`--enable-libx264` to add in the `configure` call, but you'll also have to build `libx264`), or use another codec.
